#!/usr/bin/env zsh

[ -z "$1" ] && return
: "${1:?}"
case $1 in
    (/*) FNAME="$1" ;;
    (*)  FNAME="$(pwd)/$1"
esac
export FNAME
exec osascript <<-EOF >/dev/null
    set fName to system attribute "FNAME"
    tell application "Finder" to delete my (POSIX file fName)
EOF
