#!/usr/bin/env zsh

alias jl="julia -t auto"
alias jlbase="julia -t auto -J$HOME/.local/lib/julia/base.so"
alias jlmain="julia -t auto -J$HOME/.local/lib/julia/main"
alias jlplt="julia -t auto -J$HOME/.local/lib/julia/plt"

[[ $ZSH_EVAL_CONTEXT =~ :file$ ]] || jl "$@"
