#!/usr/bin/env sh

spacebar -m config position                    top
spacebar -m config display                     all
spacebar -m config height                      28
spacebar -m config center_shell                off
spacebar -m config title                       on
spacebar -m config spaces                      on
spacebar -m config clock                       on
spacebar -m config power                       on
spacebar -m config padding_left                20
spacebar -m config padding_right               30
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15
spacebar -m config text_font                   "JetBrains Mono:Regular:17.0"
# spacebar -m config icon_font                   "Font Awesome 5 Pro:Solid:16.0"
spacebar -m config icon_font                   "FuraMono Nerd Font:Regular:18.0"
# spacebar -m config icon_font                   "JetBrains Mono:Regular:18.0"
spacebar -m config background_color            0xbb202020 #202020
spacebar -m config foreground_color            0xffa8a8a8 #A8A8A8
spacebar -m config power_icon_color            0xffcd950c #CD950C
spacebar -m config battery_icon_color          0xffd75f5f #D75F5F
spacebar -m config dnd_icon_color              0xffa8a8a8 #A8A8A8
spacebar -m config clock_icon_color            0xffa8a8a8 #A8A8A8
spacebar -m config power_icon_strip              
spacebar -m config space_icon                  •
spacebar -m config space_icon_color            0xffffab91 #ffab91
# spacebar -m config space_icon_color            0xff61b0ef #61B0EF
spacebar -m config space_icon_color_secondary  0xff78c4d4 #78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0 #fff9b0
spacebar -m config space_icon_strip            1 2 3 4 5 6 7 8 9 10
~/.config/spacebar/refresh.sh all
# spacebar -m config space_icon_strip            • • • • • • • • • •
# spacebar -m config space_icon_strip            '' '' '(  﫯)' '(﬏    )'   嗢           
spacebar -m config spaces_for_all_displays     off
# spacebar -m config spaces_for_all_displays     on
# spacebar -m config display_separator           on
# spacebar -m config display_separator_icon      ' |'

spacebar -m config clock_icon                  '  '
spacebar -m config dnd_icon                    
spacebar -m config clock_format                " %d/%m/%y  %R"
spacebar -m config right_shell                 on
spacebar -m config right_shell_icon             
spacebar -m config right_shell_command         "echo $USER"

echo "spacebar configuration loaded.."
