#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Configuration
# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.99
yabai -m config window_border                off
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xaa5DACEB
yabai -m config normal_window_border_color   0x00555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20
yabai -m config external_bar                 all:28:0

# Floating Apps
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Transmission$" manage=off
yabai -m rule --add app="^ColorSlurp$" manage=off
yabai -m rule --add app="^Free Download Manager$" manage=off
yabai -m rule --add app="^KeePassXC$" manage=off
yabai -m rule --add app="choose" manage=off sticky=on layer=above

# Auto refresh icons
# yabai -m signal --add event=space_changed action="~/.config/spacebar/refresh.sh all"
yabai -m signal --add event=space_changed action="~/.config/spacebar/refresh.sh space"
yabai -m signal --add event=application_launched action="~/.config/spacebar/refresh.sh space"
yabai -m signal --add event=application_terminated action="~/.config/spacebar/refresh.sh all"
# yabai -m signal --add event=windows_moved action="~/.config/spacebar/refresh.sh all"
yabai -m signal --add event=window_created action="~/.config/spacebar/refresh.sh space"
yabai -m signal --add event=window_destroyed action="~/.config/spacebar/refresh.sh space"


echo "yabai configuration loaded.."
